version: 2

updates:
  - package-ecosystem: uv
    versioning-strategy: increase
    directory: /
    schedule:
      interval: weekly
    assignees: [cicdbot]
    target-branch: main
    open-pull-requests-limit: 20
    labels:
      - dependencies
      - python:uv
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    assignees: [cicdbot]
    labels:
      - dependencies
      - github_actions
    commit-message:
      prefix: "ci: "
